import {
  AfterViewInit,
  Component,
  ElementRef,
  OnInit,
  ViewChild,
} from '@angular/core';
import { categories } from 'src/app/worker-categories';
import { SkillsService } from '../../service/skills.service';
import { Skills } from '../../models/skills';
import { ParishService } from '../../service/parish.service';
import { Parish } from '../../models/parish';
@Component({
  selector: 'app-workers',
  templateUrl: './workers.component.html',
  styleUrls: ['./workers.component.scss'],
})
export class WorkersComponent implements OnInit, AfterViewInit {
  categories = categories;
  currentPage = 0;
  pageLimit = 8;
  skills!: Skills[];
  parishes!: Parish[];

  @ViewChild('ele1') ele1!: ElementRef;
  @ViewChild('tabbox') tabbox!: HTMLDivElement;
  constructor(private skillService: SkillsService, private parishService:ParishService) {}

  changePage(event: any) {
    this.currentPage = event.pageIndex;
    this.pageLimit = event.pageSize;
  }

  workers = [
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
    {
      id: 1,
      name: 'Sam Baker',
      cell: '8767826546',
      image:
        'https://www.axa.co.uk/globalassets/new-website/business/carpenters/carpenter_v2_masthead.jpg?width=1600&mode=crop&heightratio=0.5625&quality=80',
      skill: 'Carpenter',
      location: 'Kingston',
      rate: 7500,
      rateType: 'Day',
      rateNegotiable: true,
      rating: 4.5,
      reviews: 52,
    },
    {
      id: 2,
      name: 'David Bannings',
      cell: '8764528797',
      image:
        'https://nigerianprice.com/wp-content/uploads/2022/05/cost-of-painting-nigeria.jpg',
      skill: 'Painter',
      location: 'Kingston',
      rate: 3100,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 3.2,
      reviews: 12,
    },
    {
      id: 3,
      name: 'Sheldon White',
      cell: '8762348936',
      image:
        'https://www.neit.edu/wp-content/uploads/2021/06/Types-of-Electricians-1024x633.jpg',
      skill: 'Electrician',
      location: 'Kingston',
      rate: 3500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 2.5,
      reviews: 32,
    },
    {
      id: 4,
      name: 'Paul Bartley',
      cell: '8768736523',
      image: 'https://www.orkin.com.jm/wp-content/uploads/2018/09/image2.jpg',
      skill: 'Pest Control',
      location: 'Kingston',
      rate: 5500,
      rateType: 'Job',
      rateNegotiable: true,
      rating: 4.8,
      reviews: 61,
    },
   ];

  ngOnInit(): void {
    this.getSkills();
    this.getParishes();
  }

  getParishes(){
    this.parishService.getAllParish().subscribe((allParishes:any) =>{
      this.parishes = allParishes.data;
    })
  }

  getSkills(){
    this.skillService.getAllSkills().subscribe((allSkills:any) =>{
      this.skills = allSkills.data;
    })
  }

  ngAfterViewInit(): void {}
}
